version: "1"

stack:
  name: sita
  description: "SITA Application Stack"

services:
  frontend:
    image:
      repository: registry.simpletactics.de/sitafrontend
    replicas: 1
    resources:
      limits:
        cpu: "0.50"
        memory: "500M"
      reservations:
        cpu: "0.25"
        memory: "250M"
    update:
      parallelism: 1
      order: start-first
    restart:
      condition: on-failure
    networks:
      - main

  backend:
    image:
      repository: registry.simpletactics.de/sitabackend
    replicas: 1
    resources:
      limits:
        cpu: "0.50"
        memory: "500M"
      reservations:
        cpu: "0.25"
        memory: "250M"
    update:
      parallelism: 1
      order: start-first
    restart:
      condition: on-failure
    environment:
      - name: TZ
        value: "Europe/Berlin"
    secrets:
      - name: DB_USERNAME
      - name: DB_PASSWORD
      - name: SITA_BOT_ALERTING_URL
    networks:
      - main

  socket:
    image:
      repository: registry.simpletactics.de/sitasocket
      tag: "1.0.0"
    replicas: 1
    resources:
      limits:
        cpu: "0.50"
        memory: "50M"
      reservations:
        cpu: "0.25"
        memory: "20M"
    update:
      parallelism: 1
      order: start-first
    restart:
      condition: on-failure
    networks:
      - main

networks:
  main:
    external: true
