name: Deploy to production

on:
  push:
    branches: [main]
    paths:
      - 'prod/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://simpletactics.de/
    steps:
      - uses: actions/checkout@v4

      - name: Validate docker compose file
        run: docker compose -f prod/docker-compose.yaml config

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          fingerprint: ${{ secrets.FINGERPRINT }}
          strip_components: 1
          source: prod/*
          target: ${{ secrets.TARGET_PATH_PROD }}
          overwrite: true

      - name: Deploy to prod
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          fingerprint: ${{ secrets.FINGERPRINT }}
          script: |
            cd ${{ secrets.TARGET_PATH_PROD }}
            bash deploy.sh ${{ secrets.STACK_NAME_PROD }}