name: Validate dev docker compose

on:
  push:
    branches-ignore: [main]
    paths:
      - 'dev/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate docker compose file
        run: docker compose -f dev/docker-compose.yaml config